export const GET_CURRENT_WEATHER_SUCCESS = 'GET_CURRENT_WEATHER_SUCCESS';
export const GET_CURRENT_WEATHER_FAIL = 'GET_CURRENT_WEATHER_FAIL';
export const SET_SELECTED_CITY = 'SET_SELECTED_CITY';
export const GET_FORECAST_SUCCESS  = 'GET_FORECAST_SUCCESS';
export const GET_FORECAST_FAIL = 'GET_FORECAST_FAIL';

